name: recaptcha
description: Example of using reCAPTCHA with Jaguar
version: 0.0.1
homepage: https://jaguar-dart.github.io/

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular2: ^3.0.0
  angular_components: ^0.5.1

dev_dependencies:
  angular_test: ^1.0.0-beta+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0
  angular_recaptcha:
  jaguar: ^0.6.5
  jaguar_recaptcha: ^ 0.0.4
  jaguar_serializer: ^0.3.10
  jaguar_json: ^0.1.2
  jaguar_auth: ^0.10.1
  jaguar_client: ^0.1.3
  jaguar_dev_proxy: ^0.0.5

transformers:
- angular2:
    entry_points: web/main.dart
- angular2/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
